USE [master]
GO

/****** Object:  Database [Customer]    Script Date: 7/04/2020 11:16:06 AM ******/
CREATE DATABASE [Customer]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Customer', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Customer.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Customer_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Customer_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Customer].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Customer] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Customer] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Customer] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Customer] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Customer] SET ARITHABORT OFF 
GO

ALTER DATABASE [Customer] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Customer] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Customer] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Customer] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Customer] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Customer] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Customer] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Customer] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Customer] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Customer] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Customer] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Customer] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Customer] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Customer] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Customer] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Customer] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Customer] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Customer] SET RECOVERY FULL 
GO

ALTER DATABASE [Customer] SET  MULTI_USER 
GO

ALTER DATABASE [Customer] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Customer] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Customer] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Customer] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Customer] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Customer] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Customer] SET  READ_WRITE 
GO



USE [Customer]
GO
--DROP TABLE [Customer]

IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[Customer]'))
BEGIN

CREATE TABLE [Customer](
[CustomerID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
[Title] [nvarchar](8) NULL,
[FirstName] [nvarchar](256) NOT NULL,
[LastName] [nvarchar](100) NOT NULL,
[EmailAddress] [nvarchar](100) NOT NULL,
[DateOfBirth] [datetime] NULL,
[MobilePhoneNo] [nvarchar](25) NULL,
[StreetAddress] [nvarchar](255) NULL,
[SuburbCity] [nvarchar](100) NULL,
[PostCode] [nvarchar](15) NULL--,
--[Country] [nvarchar](256) NULL,
--[State] [nvarchar](256) NULL,
CONSTRAINT [PK_Customer_CustomerID] PRIMARY KEY CLUSTERED
(
[CustomerID] ASC
))


END


