USE [master]
GO

/****** Object:  Database [MalindoTest]    Script Date: 7/04/2020 11:16:06 AM ******/
IF( (SELECT Count(1) FROM master.dbo.sysdatabases WHERE name = 'MalindoTest')=0)

BEGIN

CREATE DATABASE [MalindoTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MalindoTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MalindoTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MalindoTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MalindoTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )




ALTER DATABASE [MalindoTest] SET ANSI_NULL_DEFAULT OFF 


ALTER DATABASE [MalindoTest] SET ANSI_NULLS OFF 


ALTER DATABASE [MalindoTest] SET ANSI_PADDING OFF 


ALTER DATABASE [MalindoTest] SET ANSI_WARNINGS OFF 


ALTER DATABASE [MalindoTest] SET ARITHABORT OFF 


ALTER DATABASE [MalindoTest] SET AUTO_CLOSE OFF 


ALTER DATABASE [MalindoTest] SET AUTO_SHRINK OFF 


ALTER DATABASE [MalindoTest] SET AUTO_UPDATE_STATISTICS ON 


ALTER DATABASE [MalindoTest] SET CURSOR_CLOSE_ON_COMMIT OFF 


ALTER DATABASE [MalindoTest] SET CURSOR_DEFAULT  GLOBAL 


ALTER DATABASE [MalindoTest] SET CONCAT_NULL_YIELDS_NULL OFF 


ALTER DATABASE [MalindoTest] SET NUMERIC_ROUNDABORT OFF 


ALTER DATABASE [MalindoTest] SET QUOTED_IDENTIFIER OFF 


ALTER DATABASE [MalindoTest] SET RECURSIVE_TRIGGERS OFF 


ALTER DATABASE [MalindoTest] SET  DISABLE_BROKER 


ALTER DATABASE [MalindoTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 


ALTER DATABASE [MalindoTest] SET DATE_CORRELATION_OPTIMIZATION OFF 


ALTER DATABASE [MalindoTest] SET TRUSTWORTHY OFF 


ALTER DATABASE [MalindoTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 


ALTER DATABASE [MalindoTest] SET PARAMETERIZATION SIMPLE 


ALTER DATABASE [MalindoTest] SET READ_COMMITTED_SNAPSHOT OFF 


ALTER DATABASE [MalindoTest] SET HONOR_BROKER_PRIORITY OFF 


ALTER DATABASE [MalindoTest] SET RECOVERY FULL 


ALTER DATABASE [MalindoTest] SET  MULTI_USER 


ALTER DATABASE [MalindoTest] SET PAGE_VERIFY CHECKSUM  


ALTER DATABASE [MalindoTest] SET DB_CHAINING OFF 


ALTER DATABASE [MalindoTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 


ALTER DATABASE [MalindoTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 


ALTER DATABASE [MalindoTest] SET DELAYED_DURABILITY = DISABLED 


ALTER DATABASE [MalindoTest] SET QUERY_STORE = OFF


ALTER DATABASE [MalindoTest] SET  READ_WRITE 



END
GO


USE MalindoTest
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[Customer]'))
BEGIN

CREATE TABLE [Customer](
[CustomerID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
[Title] [nvarchar](8) NOT NULL,
[FirstName] [nvarchar](256) NOT NULL,
[LastName] [nvarchar](100) NOT NULL,
[EmailAddress] [nvarchar](100) NOT NULL,
[DateOfBirth] [datetime] NOT NULL,
[MobilePhoneNo] [nvarchar](25) NULL,
[StreetAddress] [nvarchar](255) NULL,
[SuburbCity] [nvarchar](100) NULL,
[PostCode] [nvarchar](15) NULL--,
CONSTRAINT [PK_Customer_CustomerID] PRIMARY KEY CLUSTERED
(
[CustomerID] ASC
))


END



